# Generated by Django 5.0.1 on 2024-02-19 09:54

import BlogApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, default='email', max_length=100)),
                ('subjects', models.CharField(max_length=500)),
                ('message', models.TextField(default='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('email', models.EmailField(default='email', max_length=100)),
                ('comment', models.TextField(default='comment')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(default='email', max_length=100)),
                ('interested', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, default='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('resume', models.FileField(upload_to='resume/')),
                ('Message', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('Job_Discription', models.TextField(max_length=1000)),
                ('Job_Location', models.CharField(default=' ', max_length=100)),
                ('Job_Type', models.CharField(default=' ', max_length=100)),
                ('No_of_Openings', models.IntegerField(default=0)),
                ('Requirements', models.ManyToManyField(to='BlogApp.job_points')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('Main_Title', models.CharField(max_length=200)),
                ('Sub_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Category', models.CharField(max_length=100)),
                ('Points_Heading', models.CharField(blank=True, max_length=100, null=True)),
                ('Paragraph1', models.TextField(max_length=1500)),
                ('Paragraph2', models.TextField(blank=True, max_length=1500, null=True)),
                ('Highlight', models.CharField(blank=True, max_length=1000, null=True)),
                ('img', models.ImageField(default='images', upload_to='images/', validators=[BlogApp.models.validate_image_size])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 24, 59, 532763))),
                ('comments', models.ManyToManyField(blank=True, null=True, to='BlogApp.comments')),
                ('points', models.ManyToManyField(blank=True, null=True, to='BlogApp.points')),
            ],
        ),
    ]
