# Generated by Django 5.0.1 on 2024-02-19 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_job_portal_max_experience_job_portal_min_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_portal',
            name='Experience',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 42, 54, 839759)),
        ),
    ]
