# Generated by Django 5.0.1 on 2024-02-19 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_remove_job_portal_experience_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 22, 0, 21, 790733)),
        ),
        migrations.AlterField(
            model_name='job_portal',
            name='Min_Experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_portal',
            name='No_of_Openings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
