# Generated by Django 5.0.1 on 2024-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0016_registration_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-15 04:17', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-15 04:17:39 PM', max_length=50),
        ),
    ]
