# Generated by Django 5.0.1 on 2024-02-18 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0017_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Contacted_person_no',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Secondary_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-18 11:20', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-18 11:20:17 PM', max_length=50),
        ),
    ]
