# Generated by Django 5.0.1 on 2024-02-19 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0018_registration_contacted_person_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-19 10:38', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 19)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-19 10:38:21 AM', max_length=50),
        ),
    ]
