# Generated by Django 5.0.1 on 2024-02-21 08:53

import hr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0020_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-21 02:23', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='attitude',
            field=models.FloatField(help_text=' marks out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='behaviour',
            field=models.FloatField(help_text=' Behaviour out of 10', null=True, validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='communicate_ability',
            field=models.FloatField(help_text=' Communicate Ability out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='confidence',
            field=models.FloatField(help_text=' Confidence out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-21 02:23:49 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='english_skils',
            field=models.FloatField(help_text='English Skils out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='executive',
            field=models.FloatField(help_text=' Executive out of 10', null=True, validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='health',
            field=models.FloatField(help_text=' Health out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='knowledge_level',
            field=models.FloatField(help_text=' Knowledge Level out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='planing',
            field=models.FloatField(help_text=' Planing out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='possitive_attitude_and_mind',
            field=models.FloatField(help_text=' Possitive attitude and mind out of 10', null=True, validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='punctuality',
            field=models.FloatField(help_text=' Punctuality out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_ability',
            field=models.FloatField(help_text=' Response Ability out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='responsibility',
            field=models.FloatField(help_text=' Responsibility out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='team_handling',
            field=models.IntegerField(help_text=' Team handling out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='understanding_level',
            field=models.FloatField(help_text=' Understanding level out of 10', validators=[hr_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='review',
            name='work_experience',
            field=models.FloatField(help_text=' Work Experience Max 25 Years', validators=[hr_app.models.validate_positive]),
        ),
    ]
