# Generated by Django 5.0.1 on 2024-02-28 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0021_alter_registration_created_at_alter_review_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ReviewedBy',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-28 04:28', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 28)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-28 04:28:05 PM', max_length=50),
        ),
    ]
