# Generated by Django 5.0.1 on 2024-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0023_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-28 04:35:40 PM', max_length=50),
        ),
    ]
