# Generated by Django 5.0.1 on 2024-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0024_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ReviewedBy',
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-28 04:49', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-28 04:49:38 PM', max_length=50),
        ),
    ]
