# Generated by Django 5.0.1 on 2024-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0030_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewedby',
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-28 10:31', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-28 10:31:20 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='ReviewedBy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
