# Generated by Django 5.0.1 on 2024-02-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0032_review_last_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-02-29 05:16', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-02-29 05:16:59 PM', max_length=50),
        ),
    ]
