# Generated by Django 5.0.1 on 2024-03-03 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0034_review_created_date_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.CharField(default='2024-03-03 03:11', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default='2024-03-03 03:11:00 PM', max_length=50),
        ),
    ]
