# Generated by Django 4.2.6 on 2023-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="name",
            field=models.CharField(default="name", max_length=100),
        ),
    ]
