# Generated by Django 5.0.1 on 2024-02-03 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Highlight',
            field=models.CharField(blank=True, default='Text', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Paragraph2',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Points_Heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sub_Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 11, 28, 47, 407215)),
        ),
    ]
