# Generated by Django 5.0.1 on 2024-02-03 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_alter_blog_highlight_alter_blog_paragraph2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Highlight',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Blog_app.comments'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 11, 31, 28, 106023)),
        ),
    ]
