# Generated by Django 5.0.1 on 2024-02-06 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0004_alter_blog_highlight_alter_blog_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 22, 8, 47, 196983)),
        ),
        migrations.RemoveField(
            model_name='job_portal',
            name='points',
        ),
        migrations.AddField(
            model_name='job_portal',
            name='points',
            field=models.ManyToManyField(to='Blog_app.job_points'),
        ),
    ]
