# Generated by Django 5.0.1 on 2024-02-06 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FtaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 22, 37, 7, 300355)),
        ),
        migrations.RemoveField(
            model_name='job_portal',
            name='points',
        ),
        migrations.AddField(
            model_name='job_portal',
            name='points',
            field=models.ManyToManyField(to='FtaApp.job_points'),
        ),
    ]
