# Generated by Django 5.0.1 on 2024-02-17 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FtaApp', '0003_contact_table_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 18, 10, 9, 699967)),
        ),
        migrations.AlterField(
            model_name='contact_table',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
