# Generated by Django 4.2.6 on 2023-12-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_code", models.CharField(max_length=6)),
                ("count_no", models.IntegerField(default=0)),
                ("offer", models.CharField(default="0%", max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
